---
development:
  dialect: postgres
  database: todosbe_development
  user: testboy
  password: testboy
  host: 127.0.0.1
  pool: 5
  port: 5432

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/todosbe_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/todosbe_production?sslmode=disable"}}
